# Generated by Django 5.2.8 on 2025-11-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('paid', 'Paid'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
